# Create a denier that returns a google.rpc.Code 7 (PERMISSION_DENIED)
apiVersion: config.istio.io/v1alpha2
kind: denier
metadata:
  name: denyall
  namespace: istio-system
spec:
  status:
    code: 7
    message: Not allowed
---
# The (empty) data handed to denyall at run time
apiVersion: config.istio.io/v1alpha2
kind: checknothing
metadata:
  name: denyrequest
  namespace: istio-system
spec:
---
# The rule that uses denier to deny requests with source.labels["app"] == "helloworld-service"
apiVersion: config.istio.io/v1alpha2
kind: rule
metadata:
  name: deny-guestbook-service
  namespace: istio-system
spec:
  match: destination.service=="guestbook-service.default.svc.cluster.local"
  actions:
  - handler: denyall.denier
    instances:
    - denyrequest.checknothing
